### Numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 3, 5, 6, 7, 9])
array1

array([1, 3, 5, 6, 7, 9])

In [4]:
print(np.zeros(5))
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(4, 17, 3))

[0. 0. 0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[ 4  7 10 13 16]


In [5]:
type(array1)

numpy.ndarray

In [10]:
array2 = np.array([[1, 2, 3, 4],[2, 3, 4, 5],[4, 5, 6, 7]])
array2.size

12

In [12]:
array2.shape

(3, 4)

### 인덱싱/슬라이싱

In [13]:
gdp_array = np.array([6610,7037,8127,8885,10385,12565,13403,12390,8282,10672])

In [15]:
gdp_array[-1]

10672

In [17]:
gdp_array[[1, 3, 4]]

array([ 7037,  8885, 10385])

In [18]:
array1 = np.array([2, 1 ,4])
gdp_array[array1]

array([ 8127,  7037, 10385])

In [19]:
gdp_array[2:6]

array([ 8127,  8885, 10385, 12565])

In [20]:
gdp_array[:6]

array([ 6610,  7037,  8127,  8885, 10385, 12565])

In [21]:
gdp_array[1:8:3]

array([ 7037, 10385, 12390])

* 2차원 array

In [23]:
gdp_array2 = np.array([
    [12257,11561,13165,14673,16496,19403], #한국
    [39169,34406,32821,35387,38299,37813], #일본
    [959,1053,1149,1289,1509,1753], #중국
    [36335,37133,38023,39496,41713,44115] #미국
])

gdp_array2

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [25]:
gdp_array2[1]

array([39169, 34406, 32821, 35387, 38299, 37813])

In [26]:
gdp_array2[1,3]

35387

In [27]:
gdp_array2[1:3, 2:5]

array([[32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [28]:
gdp_array2[1:3, 2:]

array([[32821, 35387, 38299, 37813],
       [ 1149,  1289,  1509,  1753]])

In [29]:
gdp_array2[:, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])

### 불린 인덱싱

In [33]:
mask = gdp_array > 10000
gdp_array[mask]

array([10385, 12565, 13403, 12390, 10672])

In [35]:
(gdp_array > 10000) | (gdp_array < 8000)

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True])

### Numpy 기본연산 

In [44]:
gdp_korea_array = np.array([12257, 11561 ,13165, 14673, 16496, 19403])
gdp_us_array = np.array([36335,37133,38023,39496,41713,44115])

In [42]:
gdp_korea_array.mean() # sum, min, max 도 가능

14592.5

In [43]:
gdp_korea_array * 1200

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [45]:
gdp_us_array - gdp_korea_array

array([24078, 25572, 24858, 24823, 25217, 24712])